### ISSUE TITLE
CUDA out of memory error

### ISSUE THREAD

**Issue by Chhokra** [grammarly/gector#47]
Hello folks. I'm trying to fine tune the XLNET model with some arbitrary data. The command which I'm using is

`python3 train.py --train_set=boost_train_pre --dev_set=boost_dev_pre --model_dir=XLNET_FT  --vocab_path data/output_vocabulary/ --pretrain_folder=/gector_models/  --pretrain=xlnet_0_gector  --n_epoch=10 --transformer_model=xlnet --special_tokens_fix=0`

However when I do this, I run into CUDA out of memory error. I'm using a GeForce RTX 2080 Ti. Is there something wrong with my parameters?

**Comment by komelianchuk** [comment]
Hi!
It might be an issue with long sequences in the data.
Consider using smaller batch_size and bigger accumulation_size parameters during training.

Please check whether it's working with batch_size=16, accumulation_size=8?

**Comment by Chhokra** [comment]
> Hi!
> It might be an issue with long sequences in the data.
> Consider using smaller batch_size and bigger accumulation_size parameters during training.
> 
> Please check whether it's working with batch_size=16, accumulation_size=8?

Thanks! It worked. You guys are awesome <3
