### ISSUE TITLE
RuntimeError: CUDA out of memory

### ISSUE THREAD

**Issue by yaboli** [grammarly/gector#73]
I've been following the steps and trying to reproduce the experiment results; however, during the process, I keep encountering this error:
> Traceback (most recent call last):
>   File "train.py", line 303, in <module>
>     main(args)
>   File "train.py", line 177, in main
>     trainer.train()
>   File "/workspace/gector/gector/trainer.py", line 552, in train
>     train_metrics = self._train_epoch(epoch)
>   File "/workspace/gector/gector/trainer.py", line 357, in _train_epoch
>     raise e
>   File "/workspace/gector/gector/trainer.py", line 342, in _train_epoch
>     loss = self.batch_loss(batch_group, for_training=True) / iter_len
>   File "/workspace/gector/gector/trainer.py", line 278, in batch_loss
>     output_dict = self.model(**batch)
>   File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
>     result = self.forward(*input, **kwargs)
>   File "/workspace/gector/gector/seq2labels_model.py", line 155, in forward
>     label_smoothing=self.label_smoothing)
>   File "/opt/conda/lib/python3.7/site-packages/allennlp/nn/util.py", line 619, in sequence_cross_entropy_with_logits
>     log_probs_flat = torch.nn.functional.log_softmax(logits_flat, dim=-1)
>   File "/opt/conda/lib/python3.7/site-packages/torch/nn/functional.py", line 1591, in log_softmax
>     ret = input.log_softmax(dim)
> RuntimeError: CUDA out of memory. Tried to allocate 62.00 MiB (GPU 0; 7.93 GiB total capacity; 7.06 GiB already allocated; 42.56 MiB free; 7.34 GiB reserved in total by PyTorch)

The strange thing is there seems to be more than enough GPU memory available, and also happens after two epochs are done:

```
Every 1.0s: nvidia-smi                                                                                                                                                                                 dev-oo5: Thu Nov 12 19:05:30 2020

Thu Nov 12 19:05:30 2020
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 430.50       Driver Version: 430.50       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1080    On   | 00000000:02:00.0 Off |                  N/A |
| 44%   56C    P2   160W / 200W |   1349MiB /  8117MiB |     90%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 1080    On   | 00000000:03:00.0 Off |                  N/A |
| 33%   27C    P8     7W / 200W |      0MiB /  8119MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  GeForce GTX 1080    On   | 00000000:81:00.0 Off |                  N/A |
| 33%   30C    P8     8W / 200W |      0MiB /  8119MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  GeForce GTX 1080    On   | 00000000:82:00.0 Off |                  N/A |
| 33%   27C    P8     8W / 200W |      0MiB /  8119MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0     10485      C   python                                      1339MiB |
+-----------------------------------------------------------------------------+
```
I've tried using the following code to solve it, but failed:
```
...
try:
    output_dict = self.model(**batch)
except RuntimeError as e:
    if 'out of memory' in str(e):
        print('| WARNING: ran out of memory, retrying batch',sys.stdout)
        sys.stdout.flush()
        for p in self.model.parameters():
            if p.grad is not None:
                del p.grad  # free some memory
        torch.cuda.empty_cache()
        output_dict = self.model(**batch)
    else:
        raise e
```
I've been using the exact same parameters and settings suggested by https://github.com/grammarly/gector/blob/master/docs/training_parameters.md, so I'm a bit confused about the issue I'm facing. Does anyone have any clue how I might tackle this? 
FYI: Here are the packages and their versions I'm using:
```
python==3.7.9 
torch==1.3.0
allennlp==0.8.4
python-Levenshtein==0.12.0
transformers==2.2.2
scikit-learn==0.20.0
sentencepiece==0.1.91
```

**Comment by skurzhanskyi** [comment]
Training in this work wasn't designed for multiple GPUs. I believe you need to do additional changes to run it in distributed mode. This issue https://github.com/grammarly/gector/issues/7 may be useful for you.

**Comment by yaboli** [comment]
> Training in this work wasn't designed for multiple GPUs. I believe you need to do additional changes to run it in distributed mode. This issue #7 may be useful for you.

Hi @skurzhanskyi,
I'm actually using only 1 GPU by "export CUDA_VISIBLE_DEVICES=0", so I'm not sure if it's an issue with distributed mode. But I'll look at issue #7 to see if I can find useful tips. Thanks.

**Comment by skurzhanskyi** [comment]
I see. You can try to decrease the batch size. At the same time, you may want to increase gradient accumulation steps.

**Comment by yaboli** [comment]
> I see. You can try to decrease the batch size. At the same time, you may want to increase gradient accumulation steps.

I lowered batch_size to 32 and increased accumulation_size from 4 to 8, and the runtimeerror disappeared. Thank you!

**Comment by skurzhanskyi** [comment]
Great news!
